// ─── Types ────────────────────────────────────────────────────────────────────

export type StatusType =
  | "active"
  | "invited"
  | "invitation-withdrawn"
  | "invitation-expired"
  | "blocked"
  | "grace"
  | "inactive";

export interface AccessRole {
  id: string;
  name: string;
  applications: number;
  startDate: string;
  endDate: string | null;
}

export interface User {
  id: string;
  username: string;
  firstName: string;
  lastName: string;
  phoneNumber: string;
  dateCreated: string;
  status: StatusType;
  organizations: string[];
  accessRoles?: AccessRole[];
}

// ─── Mock data ────────────────────────────────────────────────────────────────

export const baseUsers: Partial<User>[] = [
  {
    id: "1",
    username: "alison.adams@example.com",
    firstName: "Alison",
    lastName: "Adams",
    phoneNumber: "+44 123456789",
    dateCreated: "2024-07-15 11:57:50",
    status: "active",
    organizations: ["Acme Corp", "Tech Solutions", "Global Services"],
  },
  {
    id: "2",
    username: "benjamin.brown@example.com",
    firstName: "Benjamin",
    lastName: "Brown",
    phoneNumber: "+33 987654321",
    dateCreated: "2024-07-13 09:23:21",
    status: "invited",
    organizations: ["Beta Industries"],
  },
  {
    id: "3",
    username: "carla.clarke@example.com",
    firstName: "Carla",
    lastName: "Clarke",
    phoneNumber: "+39 555123456",
    dateCreated: "2024-07-12 13:15:24",
    status: "invitation-withdrawn",
    organizations: ["Gamma Ltd"],
  },
  {
    id: "4",
    username: "daniel.davies@example.com",
    firstName: "Daniel",
    lastName: "Davies",
    phoneNumber: "+49 111222333",
    dateCreated: "2024-07-12 11:42:02",
    status: "invitation-expired",
    organizations: ["Delta Partners"],
  },
  {
    id: "5",
    username: "emma.evans@example.com",
    firstName: "Emma",
    lastName: "Evans",
    phoneNumber: "+46 777888999",
    dateCreated: "2024-07-15 10:52:35",
    status: "active",
    organizations: ["Epsilon Group", "Zeta Enterprises"],
  },
  {
    id: "6",
    username: "felix.fischer@example.com",
    firstName: "Felix",
    lastName: "Fischer",
    phoneNumber: "+41 333444555",
    dateCreated: "2024-07-12 08:16:38",
    status: "active",
    organizations: ["Theta Systems"],
  },
  {
    id: "7",
    username: "george.garcia@example.com",
    firstName: "George",
    lastName: "Garcia",
    phoneNumber: "+34 666777888",
    dateCreated: "2024-07-11 11:21:05",
    status: "active",
    organizations: ["Iota Solutions", "Kappa Tech", "Lambda Consulting", "Mu Digital"],
  },
  {
    id: "8",
    username: "hannah.hughes@example.com",
    firstName: "Hannah",
    lastName: "Hughes",
    phoneNumber: "+31 999888777",
    dateCreated: "2024-07-13 08:52:38",
    status: "blocked",
    organizations: ["Nu Analytics", "Xi Networks"],
  },
  {
    id: "9",
    username: "isabel.ivanova@example.com",
    firstName: "Isabel",
    lastName: "Ivanova",
    phoneNumber: "+32 888999000",
    dateCreated: "2024-07-13 09:33:13",
    status: "grace",
    organizations: ["Omicron Ventures", "Pi Financial", "Rho Marketing", "Sigma Retail", "Tau Logistics"],
  },
  {
    id: "10",
    username: "jack.jensen@example.com",
    firstName: "Jack",
    lastName: "Jensen",
    phoneNumber: "+30 444555666",
    dateCreated: "2024-07-13 10:09:26",
    status: "blocked",
    organizations: ["Upsilon Resources", "Phi Communications"],
  },
  {
    username: "kate.kennedy@example.com",
    firstName: "Kate",
    lastName: "Kennedy",
    phoneNumber: "+45 222333444",
    dateCreated: "2024-07-14 14:22:11",
    status: "active",
    organizations: ["Chi Manufacturing", "Psi Entertainment"],
  },
  {
    username: "lucas.lopez@example.com",
    firstName: "Lucas",
    lastName: "Lopez",
    phoneNumber: "+34 111222333",
    dateCreated: "2024-07-10 16:45:30",
    status: "active",
    organizations: ["Omega Technologies", "Alpha Analytics", "Beta Healthcare"],
  },
  {
    username: "maria.martinez@example.com",
    firstName: "Maria",
    lastName: "Martinez",
    phoneNumber: "+52 555666777",
    dateCreated: "2024-07-09 10:30:45",
    status: "active",
    organizations: ["Gamma Finance"],
  },
  {
    username: "nathan.nelson@example.com",
    firstName: "Nathan",
    lastName: "Nelson",
    phoneNumber: "+1 888999000",
    dateCreated: "2024-07-11 09:15:22",
    status: "grace",
    organizations: ["Delta Consulting", "Epsilon Legal", "Zeta Real Estate", "Eta Insurance"],
  },
  {
    username: "olivia.oliver@example.com",
    firstName: "Olivia",
    lastName: "Oliver",
    phoneNumber: "+61 777888999",
    dateCreated: "2024-07-08 13:40:18",
    status: "inactive",
    organizations: ["Theta Energy"],
  },
  {
    username: "peter.parker@example.com",
    firstName: "Peter",
    lastName: "Parker",
    phoneNumber: "+1 555444333",
    dateCreated: "2024-07-14 11:25:50",
    status: "active",
    organizations: ["Iota Education", "Kappa Travel"],
  },
  {
    username: "quinn.quinn@example.com",
    firstName: "Quinn",
    lastName: "Quinn",
    phoneNumber: "+353 666555444",
    dateCreated: "2024-07-07 15:10:35",
    status: "active",
    organizations: ["Lambda Food", "Mu Beverage", "Nu Hospitality"],
  },
  {
    username: "rachel.rogers@example.com",
    firstName: "Rachel",
    lastName: "Rogers",
    phoneNumber: "+44 333222111",
    dateCreated: "2024-07-12 08:55:42",
    status: "blocked",
    organizations: ["Xi Fashion", "Omicron Luxury"],
  },
  {
    username: "steve.smith@example.com",
    firstName: "Steve",
    lastName: "Smith",
    phoneNumber: "+1 444333222",
    dateCreated: "2024-07-06 12:30:20",
    status: "grace",
    organizations: ["Pi Sports"],
  },
  {
    username: "thomas.thompson@example.com",
    firstName: "Thomas",
    lastName: "Thompson",
    phoneNumber: "+1 555666777",
    dateCreated: "2024-07-15 09:20:15",
    status: "active",
    organizations: ["Rho Media", "Sigma Publishing", "Tau Broadcasting", "Upsilon Streaming"],
  },
  {
    username: "uma.upadhyay@example.com",
    firstName: "Uma",
    lastName: "Upadhyay",
    phoneNumber: "+91 8899001122",
    dateCreated: "2024-07-14 14:35:40",
    status: "active",
    organizations: ["Phi Software", "Chi Hardware"],
  },
  {
    username: "victor.victor@example.com",
    firstName: "Victor",
    lastName: "Victor",
    phoneNumber: "+33 111222333",
    dateCreated: "2024-07-13 10:15:25",
    status: "active",
    organizations: ["Psi Automotive", "Omega Defense", "Alpha Security", "Beta Telecommunications", "Gamma Aerospace"],
  },
  {
    username: "wendy.williams@example.com",
    firstName: "Wendy",
    lastName: "Williams",
    phoneNumber: "+1 777888999",
    dateCreated: "2024-07-12 16:45:50",
    status: "active",
    organizations: ["Delta Mining", "Epsilon Agriculture"],
  },
  {
    username: "xavier.xu@example.com",
    firstName: "Xavier",
    lastName: "Xu",
    phoneNumber: "+86 2233445566",
    dateCreated: "2024-07-11 11:30:20",
    status: "active",
    organizations: ["Zeta Utilities", "Eta Construction"],
  },
  {
    username: "yara.young@example.com",
    firstName: "Yara",
    lastName: "Young",
    phoneNumber: "+44 555666777",
    dateCreated: "2024-07-10 13:20:35",
    status: "active",
    organizations: ["Theta Transportation", "Iota Logistics", "Kappa Distribution"],
  },
  {
    username: "zoe.zimmerman@example.com",
    firstName: "Zoe",
    lastName: "Zimmerman",
    phoneNumber: "+49 222333444",
    dateCreated: "2024-07-09 15:50:10",
    status: "active",
    organizations: ["Lambda Warehousing"],
  },
  {
    id: "0",
    username: "alice.anderson@example.com",
    firstName: "Alice",
    lastName: "Anderson",
    phoneNumber: "+1 888999000",
    dateCreated: "2024-07-15 08:25:45",
    status: "active",
    organizations: ["InsurCar"],
    accessRoles: [
      {
        id: "1",
        name: "Claim processor",
        applications: 5,
        startDate: "19/09/2024",
        endDate: "18/09/2024",
      },
      {
        id: "2",
        name: "Front desk person",
        applications: 3,
        startDate: "19/09/2024",
        endDate: null,
      },
      {
        id: "3",
        name: "Underwriting Analyst",
        applications: 5,
        startDate: "19/09/2024",
        endDate: "18/09/2024",
      },
    ],
  },
  {
    username: "brandon.brennan@example.com",
    firstName: "Brandon",
    lastName: "Brennan",
    phoneNumber: "+61 3344556677",
    dateCreated: "2024-07-14 12:10:30",
    status: "active",
    organizations: ["Xi Ecommerce", "Omicron Digital"],
  },
  {
    username: "charlotte.chen@example.com",
    firstName: "Charlotte",
    lastName: "Chen",
    phoneNumber: "+86 5566778899",
    dateCreated: "2024-07-13 14:40:20",
    status: "active",
    organizations: ["Pi Analytics", "Rho Data", "Sigma Cloud"],
  },
  {
    username: "david.dunn@example.com",
    firstName: "David",
    lastName: "Dunn",
    phoneNumber: "+1 222333444",
    dateCreated: "2024-07-12 10:05:15",
    status: "active",
    organizations: ["Tau Consulting"],
  },
  {
    username: "emily.edwards@example.com",
    firstName: "Emily",
    lastName: "Edwards",
    phoneNumber: "+44 666777888",
    dateCreated: "2024-07-11 15:30:50",
    status: "active",
    organizations: ["Upsilon Marketing", "Phi Advertising"],
  },
  {
    username: "frank.fleming@example.com",
    firstName: "Frank",
    lastName: "Fleming",
    phoneNumber: "+33 555666777",
    dateCreated: "2024-07-10 09:45:25",
    status: "active",
    organizations: ["Chi PR"],
  },
  {
    username: "grace.grant@example.com",
    firstName: "Grace",
    lastName: "Grant",
    phoneNumber: "+1 111222333",
    dateCreated: "2024-07-09 16:20:40",
    status: "active",
    organizations: ["Psi Design", "Omega Branding", "Alpha UX", "Beta Visual"],
  },
  {
    username: "henry.harris@example.com",
    firstName: "Henry",
    lastName: "Harris",
    phoneNumber: "+49 333444555",
    dateCreated: "2024-07-15 13:15:10",
    status: "active",
    organizations: ["Gamma Creative"],
  },
  {
    username: "iris.ingram@example.com",
    firstName: "Iris",
    lastName: "Ingram",
    phoneNumber: "+61 4455667788",
    dateCreated: "2024-07-14 11:50:35",
    status: "active",
    organizations: ["Delta Development", "Epsilon Quality", "Zeta Testing"],
  },
  {
    username: "james.jackson@example.com",
    firstName: "James",
    lastName: "Jackson",
    phoneNumber: "+1 333444555",
    dateCreated: "2024-07-13 09:30:20",
    status: "active",
    organizations: ["Eta DevOps"],
  },
  {
    username: "karen.kemp@example.com",
    firstName: "Karen",
    lastName: "Kemp",
    phoneNumber: "+44 777888999",
    dateCreated: "2024-07-12 14:25:45",
    status: "active",
    organizations: ["Theta Infrastructure", "Iota Cloud"],
  },
  {
    username: "leon.lewis@example.com",
    firstName: "Leon",
    lastName: "Lewis",
    phoneNumber: "+33 666777888",
    dateCreated: "2024-07-11 10:40:15",
    status: "active",
    organizations: ["Kappa Systems", "Lambda Networks", "Mu Servers", "Nu Database", "Xi Storage"],
  },
  {
    username: "maggie.miller@example.com",
    firstName: "Maggie",
    lastName: "Miller",
    phoneNumber: "+1 444555666",
    dateCreated: "2024-07-10 15:55:30",
    status: "active",
    organizations: ["Omicron Security"],
  },
  {
    username: "noah.norman@example.com",
    firstName: "Noah",
    lastName: "Norman",
    phoneNumber: "+49 444555666",
    dateCreated: "2024-07-09 12:30:50",
    status: "active",
    organizations: ["Pi Monitoring", "Rho Alerting"],
  },
  {
    username: "oscar.owen@example.com",
    firstName: "Oscar",
    lastName: "Owen",
    phoneNumber: "+61 5566778899",
    dateCreated: "2024-07-15 10:15:20",
    status: "active",
    organizations: ["Sigma Automation", "Tau Orchestration"],
  },
  {
    username: "paul.perry@example.com",
    firstName: "Paul",
    lastName: "Perry",
    phoneNumber: "+1 555666777",
    dateCreated: "2024-07-14 16:40:35",
    status: "active",
    organizations: ["Upsilon Configuration"],
  },
  {
    username: "quinn.quinn2@example.com",
    firstName: "Quinn",
    lastName: "Quinn",
    phoneNumber: "+44 888999000",
    dateCreated: "2024-07-13 13:25:10",
    status: "active",
    organizations: ["Phi Backup", "Chi Recovery"],
  },
  {
    username: "ruby.robinson@example.com",
    firstName: "Ruby",
    lastName: "Robinson",
    phoneNumber: "+33 777888999",
    dateCreated: "2024-07-12 11:50:45",
    status: "active",
    organizations: ["Psi Migration", "Omega Integration", "Alpha Synchronization"],
  },
  {
    username: "samuel.sanders@example.com",
    firstName: "Samuel",
    lastName: "Sanders",
    phoneNumber: "+1 666777888",
    dateCreated: "2024-07-11 14:10:20",
    status: "active",
    organizations: ["Beta Validation"],
  },
  {
    username: "tina.taylor@example.com",
    firstName: "Tina",
    lastName: "Taylor",
    phoneNumber: "+49 555666777",
    dateCreated: "2024-07-10 10:35:30",
    status: "active",
    organizations: ["Gamma Performance", "Delta Optimization"],
  },
  {
    username: "uncle.usher@example.com",
    firstName: "Uncle",
    lastName: "Usher",
    phoneNumber: "+61 6677889900",
    dateCreated: "2024-07-09 15:45:15",
    status: "active",
    organizations: ["Epsilon Compliance", "Zeta Governance", "Eta Risk", "Theta Audit"],
  },
];

// ─── Derived data & helpers ───────────────────────────────────────────────────

export const users: User[] = baseUsers.map(
  (user, index) =>
    ({
      ...user,
      id: user.id || (index + 1).toString(),
    }) as User,
);

export function getUserById(id: string): User | undefined {
  return baseUsers.find((user) => user.id === id) as User | undefined;
}

export function getUserByUsername(username: string): User | undefined {
  return baseUsers.find((user) => user.username === username) as User | undefined;
}
